// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkHDC_HaB17njqLv__dc5jW3g5dHz7LJg',
    appId: '1:398534187117:web:9130935b2abcd3c2f00764',
    messagingSenderId: '398534187117',
    projectId: 'the-movie-journal',
    authDomain: 'the-movie-journal.firebaseapp.com',
    storageBucket: 'the-movie-journal.firebasestorage.app',
    measurementId: 'G-C8N33K1TQV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALwTyTR2W_PoAa35q8bBabX9RwZbtjIBI',
    appId: '1:398534187117:android:5d322aab2d2c19b2f00764',
    messagingSenderId: '398534187117',
    projectId: 'the-movie-journal',
    storageBucket: 'the-movie-journal.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIDB2tC1u-7F0H0D6aCwmXWfvJHv_nVjg',
    appId: '1:398534187117:ios:fd7ad4c041d260dbf00764',
    messagingSenderId: '398534187117',
    projectId: 'the-movie-journal',
    storageBucket: 'the-movie-journal.firebasestorage.app',
    iosBundleId: 'com.isaackwok.moviejournal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCIDB2tC1u-7F0H0D6aCwmXWfvJHv_nVjg',
    appId: '1:398534187117:ios:173d8df78eb8cbf6f00764',
    messagingSenderId: '398534187117',
    projectId: 'the-movie-journal',
    storageBucket: 'the-movie-journal.firebasestorage.app',
    iosBundleId: 'com.example.movieJournal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBkHDC_HaB17njqLv__dc5jW3g5dHz7LJg',
    appId: '1:398534187117:web:45321da3d0908372f00764',
    messagingSenderId: '398534187117',
    projectId: 'the-movie-journal',
    authDomain: 'the-movie-journal.firebaseapp.com',
    storageBucket: 'the-movie-journal.firebasestorage.app',
    measurementId: 'G-6LZQ43CTNC',
  );

}